 # -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hollywood-" + ENV['TCPH_KERNEL_REV']
  config.vm.box_url = "stage1/hollywood-" + ENV['TCPH_KERNEL_REV'] + ".box"
  config.vm.boot_timeout = 600
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end
end
